# Generated by Django 2.2.10 on 2020-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstbook', '0002_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=24)),
                ('postcode', models.CharField(max_length=23)),
                ('type', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('payment', models.CharField(max_length=250)),
            ],
        ),
    ]
