# Generated by Django 2.2.10 on 2020-10-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstbook', '0004_auto_20201017_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='photo',
        ),
    ]
