# Generated by Django 2.2.10 on 2020-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstbook', '0005_remove_apply_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='application/pdfs/')),
            ],
        ),
    ]
