# Generated by Django 2.2.10 on 2020-10-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstbook', '0006_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='permission',
        ),
    ]
